#pragma once

#include "Dictionary.h"
#include "HashDictionary.h"
#include "ICollection.h"
#include "IDictionary.h"
#include "IList.h"
#include "IReadOnlyCollection.h"
#include "ISet.h"
#include "KeyValuePair.h"
#include "List.h"
#include "LinkedList.h"
#include "Queue.h"
#include "SortedDictionary.h"
#include "SortedSet.h"
#include "SortedList.h"
#include "Stack.h"